baseURL: "https://paultraylor.net"
languageCode: "en-us"
title: "PaulTraylor.net"
theme:
  - worklog
  - bootstrap
rssLimit: 10

params:
  twitter: "https://twitter.com/kfdm"
  github: https://github.com/kfdm
  header:
    colorScheme: dark
  mainSections:
    - blog
    - week

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: project
      name: Projects
      url: /project/
      weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: week
      name: Week Notes
      url: /week/
      weight: 40
    - name: 日本語
      url: https://nihongo.paultraylor.net/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
