baseURL: "https://paultraylor.net/"
languageCode: "en-us"
title: "PaulTraylor.net"
theme:
  - worklog
  - bootstrap
rssLimit: 10

params:
  social:
    GitHub: https://github.com/kfdm
    Twitter: "https://twitter.com/kfdm"
    Instagram: https://www.instagram.com/kungfudiscomonkey/
    Mastodon: https://mastodon.social/@kfdm
    LinkedIn: https://www.linkedin.com/in/PaulTraylor
    Wakatime: https://wakatime.com/@kfdm
  header:
    colorScheme: dark
  mainSections:
    - blog
    - week
    - share
    - project

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: project
      name: Projects
      url: /project/
      weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: share
      name: Shares
      url: /share/
      weight: 30
    - identifier: week
      name: Week Notes
      url: /week/
      weight: 40
    - name: 日本語
      url: https://nihongo.paultraylor.net/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

taxonomies:
  category: categories
  tag: tags
  status: status
